### ISSUE TITLE
Call to a member function delete() on null

### ISSUE THREAD

**Issue by kyranb** [michaeldyrynda/laravel-cascade-soft-deletes#10]
I'm receiving the following error when deleting a model using this trait.

`FatalThrowableError in CascadeSoftDeletes.php line 40:
Call to a member function delete() on null`

Full stack trace:

```
in CascadeSoftDeletes.php line 40
at Post::Iatstuti\Database\Support\{closure}(object(Post))
at call_user_func_array(object(Closure), array(object(Post))) in Dispatcher.php line 221
at Dispatcher->fire('eloquent.deleting: App\Post', array(object(Post)), true) in Dispatcher.php line 164
at Dispatcher->until('eloquent.deleting: App\Post', object(Post)) in Model.php line 1686
at Model->fireModelEvent('eloquent.deleting: App\Post') in Model.php line 1122
at Model->delete() in PostsController.php line 142
```

The `$child` variable here in the trait is returning null.
```php
$delete = $model->forceDeleting ? 'forceDelete' : 'delete';

            foreach ($model->getCascadingDeletes() as $relationship) {
                foreach ($model->{$relationship} as $child) {
                    $child->{$delete}();
                }
            }
```

I must be missing something obvious because testing it like so, it appears that $child is not being set when the for loop runs.

```php
dd($model->getCascadingDeletes()); // returns ['website'] (the model relationship to be deleted)

 foreach ($model->getCascadingDeletes() as $relationship) {
                foreach ($model->{$relationship} as $child) {
                    dd($child); // returns Null
                    dd($model->{$relationship}); // returns the cascading model to be deleted. 
                    $child->{$delete}();
                }
            }
```

If anyone can point me in the right direction what I or this package is doing wrong, that would be much appreciated :)

**Comment by michaeldyrynda** [comment]
Interesting. Is the `website` a `hasOne` relationship, by any chance?

A failing test would be really helpful in not only pinpointing the issue but also applying an appropriate fix.

It may be that a child relationship isn't set and it's just a matter of adding a `null` check in the delete logic, but I'm not able to reproduce, so it's difficult to make an appropriate fix.

**Comment by kyranb** [comment]
Yes it is a has one relationship  :)

**Comment by michaeldyrynda** [comment]
Can you cast the inner `foreach` to an array?

`foreach ((array) $model->{$relationship} as $child) {`

**Comment by michaeldyrynda** [comment]
I think I know how to fix this one, let me look at it in a few hours.

**Comment by michaeldyrynda** [comment]
I have a rough idea of why this is happening and should have a fix available soon-ish

**Comment by kyranb** [comment]
Thanks :)
