### ISSUE TITLE
Feature suggestion for cascade restore

### ISSUE THREAD

**Issue by hsarnaud** [michaeldyrynda/laravel-cascade-soft-deletes#16]
Quoting from the readme

> Note: It's important to know that when you cascade your soft deleted child records, there is no way to know which were deleted by the cascading operation, and which were deleted prior to that. This means that when you restore the blog post, the associated comments will not be.

I just verified that the deleted_at timestamp does not get overwritten if records were deleted prior to the cascade delete happening. So it means that yes you can know which were deleted before or not by matching the timestamp with the one on the parent that was deleted. This means that technically, the restore operation on a blog post could restore any comments that have a (maybe nearly) exact timestamp. So yes this is technically possible.

**Comment by michaeldyrynda** [comment]
I wouldn't rely on the timestamp, especially once you start getting into larger datasets being cascaded, you'll get some time drift, so it's prone to error at scale.

**Comment by michaeldyrynda** [comment]
I'm going to close this one off. Restoring previously deleted cascades won't be handled by this package.

**Comment by SamuelYute** [comment]
A suggestion on this matter would be, to instantiate a freshTimestamp which would be used as 'deleted_at ' field for all models deleted in the cascade. So during restore, you simply use the parent deleted_at timestamp to match with all the cascaded relations that match the 'deleted_at'. This reduces the error margin of getting other models which weren't cascaded in the operation. To make it better, you can use Timestamps with a precision of milliseconds to make sure there is no margin of error.

I have tried it and it has worked.
Check Code below

`<?php
namespace App\Http\Traits;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Database\Eloquent\SoftDeletes;
use LogicException;

trait CascadeSoftDeletes
{
    use SoftDeletes;

        /**
     *  Determine if the Cascading Restore should be done for model relationships
     *
     *  @default true
     */
    protected $shouldCascadeRestore = true;

    /**
     *  The Timestamp that will be set at the 'Deleted at' attribute of model
     *  relationships on soft delete cascade
     *
     *  @default null
     */
    protected $parentDeletedAt = null;

    /**
     * Overridden 'Delete the model from the database'.
     *
     * @param $parentDeletedAt = null
     *
     * @return bool|null
     *
     * @throws \Exception
     */
    public function delete($parentDeletedAt = null)
    {
        if (is_null($this->getKeyName())) {
            throw new Exception('No primary key defined on model.');
        }

        // If the model doesn't exist, there is nothing to delete so we'll just return
        // immediately and not do anything else. Otherwise, we will continue with a
        // deletion process on the model, firing the proper events, and so forth.
        if (! $this->exists) {
            return;
        }

        $this->parentDeletedAt = $parentDeletedAt;

        if ($this->shouldCascadeRestore && is_null($this->parentDeletedAt) ) {
            $this->deleted_at = $this->parentDeletedAt = $this->freshTimestamp();
        }


        if ($this->fireModelEvent('deleting') === false) {
            return false;
        }

        // Here, we'll touch the owning models, verifying these timestamps get updated
        // for the models. This will allow any caching to get broken on the parents
        // by the timestamp. Then we will go ahead and delete the model instance.
        $this->touchOwners();

        $this->performDeleteOnModel();

        // Once the model has been deleted, we will fire off the deleted event so that
        // the developers may hook into post-delete operations. We will then return
        // a boolean true as the delete is presumably successful on the database.
        $this->fireModelEvent('deleted', false);

        return true;
    }


    /**
     * Overridden 'Perform the actual delete query on this model instance.'
     *
     *
     * @return void
     */
    protected function runSoftDelete()
    {
        $query = $this->newQueryWithoutScopes()->where($this->getKeyName(), $this->getKey());

        $time = !is_null($this->parentDeletedAt)?$this->parentDeletedAt:$this->freshTimestamp();

        $columns = [$this->getDeletedAtColumn() => $this->fromDateTime($time)];

        $this->{$this->getDeletedAtColumn()} = $time;

        if ($this->timestamps && ! is_null($this->getUpdatedAtColumn())) {
            $this->{$this->getUpdatedAtColumn()} = $time;

            $columns[$this->getUpdatedAtColumn()] = $this->fromDateTime($time);
        }

        $query->update($columns);
    }


    /**
     * Boot the trait.
     *
     * Listen for the deleting event of a soft deleting model, and run
     * the delete operation for any configured relationship methods.
     *
     * @throws \LogicException
     */
    protected static function bootCascadeSoftDeletes()
    {
        static::deleting(function ($model) {

            $model->validateCascade();

            $delete = $model->forceDeleting ? 'forceDelete' : 'delete';

            foreach ($model->getActiveCascadingDeletes() as $relationship) {
                if ($model->{$relationship} instanceof Model) {
                    $model->{$relationship}->{$delete}($model->deleted_at);
                } else {

                    foreach ($model->{$relationship} as $child) {
                        $child->{$delete}($model->deleted_at);
                    }
                }
            }
        });

        static::restoring(function ($model) {

            $model->validateCascade();

            foreach ($model->getCascadingDeletes() as $relationship) {
                $children = $model->{$relationship}()
                                    ->onlyTrashed()
                                    ->where('deleted_at', $model->deleted_at)
                                    ->get();

                foreach ($children as $child) {
                    $child->restore();
                }
            }
        });
    }




    /**
     * Determine if the current model implements soft deletes.
     *
     *
     */
    protected function validateCascade()
    {
        if (! $this->implementsSoftDeletes()) {
            throw new LogicException(sprintf(
                '%s does not implement Illuminate\Database\Eloquent\SoftDeletes',
                get_called_class()
            ));
        }

        if ($invalidCascadingRelationships = $this->hasInvalidCascadingRelationships()) {
            throw new LogicException(sprintf(
                '%s [%s] must exist and return an object of type Illuminate\Database\Eloquent\Relations\Relation',
                str_plural('Relationship', count($invalidCascadingRelationships)),
                join(', ', $invalidCascadingRelationships)
            ));
        }
    }

    /**
     * Determine if the current model implements soft deletes.
     *
     * @return bool
     */
    protected function implementsSoftDeletes()
    {
        return method_exists($this, 'runSoftDelete');
    }

    /**
     * Determine if the current model has any invalid cascading relationships defined.
     *
     * A relationship is considered invalid when the method does not exist, or the relationship
     * method does not return an instance of Illuminate\Database\Eloquent\Relations\Relation.
     *
     * @return array
     */
    protected function hasInvalidCascadingRelationships()
    {
        return array_filter($this->getCascadingDeletes(), function ($relationship) {
            return ! method_exists($this, $relationship) || ! $this->{$relationship}() instanceof Relation;
        });
    }
    /**
     * Fetch the defined cascading soft deletes for this model.
     *
     * @return array
     */
    protected function getCascadingDeletes()
    {
        return isset($this->cascadeDeletes) ? (array) $this->cascadeDeletes : [];
    }
    /**
     * For the cascading deletes defined on the model, return only those that are not null.
     *
     * @return array
     */
    protected function getActiveCascadingDeletes()
    {
        return array_filter($this->getCascadingDeletes(), function ($relationship) {
            return ! is_null($this->{$relationship});
        });
    }
}`

Then you use the it in your model as so

`<?php

namespace App\Modules\Priority\Academics\Faculties\Data\Models;

use App\Http\Traits\CascadeSoftDeletes;
use App\Modules\Priority\Academics\Departments\Data\Models\Department;
use App\Modules\Priority\Academics\Programmes\Data\Models\Programme;
use App\Modules\Priority\Profiles\Teachers\Data\Models\Teacher;
use Illuminate\Database\Eloquent\Model;

class Faculty extends Model
{
    use CascadeSoftDeletes;

    protected $cascadeDeletes = ['departments'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','slug','description'
    ];

    public function programmes()
    {
        return $this->hasMany(Programme::class);
    }

    public function departments()
    {
        return $this->hasMany(Department::class);
    }

    public function deans()
    {
        return $this->belongsToMany(Teacher::class,'faculty_deans')
                    ->withPivot(['type'])
                    ->withTimestamps();
    }

    public function facultyDeans()
    {
        return $this->hasMany(FacultyDean::class,'faculty_id');
    }

    public function getDisplayNameAttribute()
    {
        return "Faculty of ".$this->name;
    }
}
`

There Done.

Works for HasOne and HasMany
