### ISSUE TITLE
Why looping over models ?

### ISSUE THREAD

**Issue by nicolas-t** [michaeldyrynda/laravel-cascade-soft-deletes#19]
Hi!

here:
https://github.com/michaeldyrynda/laravel-cascade-soft-deletes/blob/master/src/CascadeSoftDeletes.php#L43L45

Why do you loop over models instead of just using: `$model->{$relationship}->{$delete}();` ,
If I delete a post having hundreds of asociated comments, wouldn't it be very costly to delete them one by one ?

Thanks

**Comment by michaeldyrynda** [comment]
You're correct and I was looking for a way to optimise this, but I'm not sure there really is one at the application level. This was added as part of a [PR](https://github.com/michaeldyrynda/laravel-cascade-soft-deletes/pull/9) to support deleting of grandchild records.

If you call `$model->{$relationship}->{$delete}()` it will run a `DELETE FROM <table> WHERE <foreign_id> IN (...)`, which means that no `deleted` event will fire on those records, as the model isn't instantiated.

As your application grows and the number of records increases, cascading soft deletes really starts to lose its value in terms of performance.

If you have any suggestions on a better way to handle this, I'd love to hear it, though!

**Comment by nicolas-t** [comment]
Thanks; 

I don't think there is an other solution than looping over models.
