### ISSUE TITLE
Order of 'deleting' listeners

### ISSUE THREAD

**Issue by mattpramschufer** [michaeldyrynda/laravel-cascade-soft-deletes#21]
First your package is great.  works perfect.  The issue that I am having is that I have my own event listeners for a model for 'deleting' your trait is firing before my deleting listener, I was wondering if you knew of a way to have it so my  local model listener fired before your trait deleting listener.

Just to give you an example.  I have a Model called Runs which has many Runners attached to it.  I have an event setup for when a Run gets deleted to send a notification to all Runners that the run was deleted.  Since your trait is cascading down to runners first, when i go to grab a collection of runners $run->runners()->get();  It returns 0 because they were already soft deleted.

**Comment by dangreaves** [comment]
Although undocumented, you can actually pass in a priority when registering an eloquent event listener. I haven't tested it but presumably setting the priority to `-1` or `1` when you register your own listener will place it ahead of the listener registered in the trait.

```php
static::deleting($callaback, $priority);
```

https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L1274

**Comment by michaeldyrynda** [comment]
Hey @mattpramschufer, thanks for the report. I'm not sure about this and hadn't considered this case - where other listeners or events would be fired, but sounds like what @dangreaves might be what you're after.

If so, we can look at updating the package docs with this information, if you were happy to submit a PR for that?

**Comment by mattpramschufer** [comment]
Thanks @dangreaves and @michaeldyrynda that worked like a champ!  Let me look into getting a PR for you.  The default priority is 0, so I set my local listener to priority 1.  Coming from Wordpress I was unsure about this because with Wordpress 0 is the highest priority, with Laravel 0 is the lowest priority.

**Comment by mattpramschufer** [comment]
Pull Request Submitted.  Thanks again.
