### ISSUE TITLE
is foreign key relationship mandatory for this to work?

### ISSUE THREAD

**Issue by mailnike** [michaeldyrynda/laravel-cascade-soft-deletes#24]
Hi,

Is foreign key relationship mandatory for this to work? Also, is it possible that ver 1.2 doesn't work with Larval 5.3?

Thanks.

**Comment by michaeldyrynda** [comment]
Hey @mailnike - you don't need a foreign key, just a defined relationship on the model.

Is there some specific issue you're encountering with Laravel 5.3?

**Comment by mailnike** [comment]
Oh okay. Actually I followed all the steps, but somehow it didn't work for me. Let me share the code. Meanwhile I will close this.
