### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by rabol** [michaeldyrynda/laravel-cascade-soft-deletes#28]
Hi

I have a project that is based on the Laravel 5.8 Boilerplate.

I have the following two models:

````
ERecipe
ERecipeIngredients

in the main I have this:

    protected $cascadeDeletes = ['e_ingredients'];

    public function e_ingredients()
    {
        return $this->hasMany(ERecipeIngredient::class,'recipe_id','id');
    }

````

But when deleting the Erecipe, the child records does not get deleted

e_ingredients returns: Illuminate\Database\Eloquent\Relations\HasMany

**Comment by exitttttt** [comment]
How do you delete ERecipe ? Because as state in the laravel documentation (https://laravel.com/docs/5.8/eloquent#soft-deleting) mass delete will not trigger the event "deleting" so this plugin will not work in this case.

I'm using laravel 5.8 and the plugin does work for me.

**Comment by michaeldyrynda** [comment]
If you are calling `$erecipe->e_ingredients()->delete()`, this will not trigger model events as it runs a `delete` query directly against the database.
