### ISSUE TITLE
What if onDelete is restrict instead of cascade?

### ISSUE THREAD

**Issue by rohanvakharia** [michaeldyrynda/laravel-cascade-soft-deletes#3]
I have model which uses soft delete but the action for `onDelete` is `restrict` instead of `cascade`.
I have gonna through your code and you haven't handling this case.

Can you be able to provide any solution to check the type of `onDelete` action if  the type `restrict` then do not delete and show error?

**Comment by michaeldyrynda** [comment]
If you are using the `SoftDeletes` trait, then calling the `delete()` method on your model will only update the `deleted_at` field in your database, and the `onDelete` constraint will not be triggered, given that it is triggered at the database level i.e. when a `DELETE` query is executed.

This package has no knowledge of foreign key constraints that are defined using the `onDelete` constraint. If you do have that constraint defined on your foreign key, it will only be triggered if you call the `forceDelete()` method on your model, at which point I believe Laravel will throw a database exception of some description..

**Comment by rohanvakharia** [comment]
Yes I completely agree and aware about the `softDelete` flow. But want to retain the data in database even though it was deleted from application.
Is there any way I can raise database foreign key constraint violation alert with `softDelete`?

**Comment by michaeldyrynda** [comment]
Not to my knowledge, let me think on it for a bit.

**Comment by michaeldyrynda** [comment]
I'm going to close this one off. Having `restrict` logic is something that is not catered to by `laravel/framework`, which this package is an extension to. The intention of this package is to only cascade the deletes, not introduce additional functionality.

**Comment by kobalazs** [comment]
Did an experimental package doing exactly that - it sends an Exception when you attempt to delete a model with restricted relations. Implementation is based on Michael's idea, feel free to contribute here: https://github.com/kobalazs/laravel-restrict-soft-deletes
