### ISSUE TITLE
How to wotrk with pivot models?

### ISSUE THREAD

**Issue by max-petrovich** [michaeldyrynda/laravel-cascade-soft-deletes#30]
BelongsToMany implies using pivot tables. How to soft delete only pivot records without realted  through pivot records?

**Comment by FerCruzBanegas** [comment]
any news about this? i need the same

**Comment by max-petrovich** [comment]
I have implemented a separate relation for the pivot table and use it. Maybe this is a more flexible solution.

**Comment by michaeldyrynda** [comment]
Resolved by #34

**Comment by phillipsharring** [comment]
In the case of the pivot - in the migration - would we add `$table->softDeletes()` to the pivot table? Is that only useful if there's a pivot for the model. And if not, is this package able to use the relationship and go "though" the pivot table and soft delete the related model? Thanks :)
