### ISSUE TITLE
Support for Laravel 7

### ISSUE THREAD

**Issue by monsterdream** [michaeldyrynda/laravel-cascade-soft-deletes#38]
Hi,
It seems that package has a conflict with newest version of Laravel 7. Most likely that one seems to be problematic:

"don't install illuminate/events 6.x-dev|don't install laravel/framework 7.x-dev"

**Comment by michaeldyrynda** [comment]
Closed by #37, tagged as [3.0.0](https://github.com/michaeldyrynda/laravel-cascade-soft-deletes/releases/tag/3.0.0)
