### ISSUE TITLE
Issue in composer install laravel-cascade-soft-deletes

### ISSUE THREAD

**Issue by manoj12345678** [michaeldyrynda/laravel-cascade-soft-deletes#43]
Hi 

I am using laravel 7.3 when i run this command 'composer require dyrynda/laravel-cascade-soft-deletes'

I have get this error :
Problem 1
    - Root composer.json requires dyrynda/laravel-cascade-soft-deletes ^4.0 -> satisfiable by dyrynda/laravel-cascade-soft-deletes[4.0.0].
    - dyrynda/laravel-cascade-soft-deletes 4.0.0 requires illuminate/database ^8.0 -> found illuminate/database[v8.0.0, ..., v8.13.0] but it conflicts with another require.

I am unable to found root casue can you please check this.

**Comment by michaeldyrynda** [comment]
I just created a fresh Laravel 7.3 project and installed the package with no problem.

It appears you have some conflict within your application preventing installation.

What happens if you run `composer require dyrynda/laravel-cascade-soft-deletes --with-dependencies`?

**Comment by nagi1** [comment]
same problem 

`$ composer require dyrynda/laravel-cascade-soft-deletes --with-dependencies
Using version ^4.1 for dyrynda/laravel-cascade-soft-deletes
./composer.json has been updated
Running composer update dyrynda/laravel-cascade-soft-deletes --with-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dyrynda/laravel-cascade-soft-deletes ^4.1 -> satisfiable by dyrynda/laravel-cascade-soft-deletes[4.1.0].
    - dyrynda/laravel-cascade-soft-deletes 4.1.0 requires illuminate/database ^8.12 -> found illuminate/database[v8.12.0, ..., 8.x-dev] but it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

**Comment by erwinangeles** [comment]
Hello. I am also having this issue with Laravel 7.30.1.

$composer require dyrynda/laravel-cascade-soft-deletes --with-dependencies
Using version ^4.1 for dyrynda/laravel-cascade-soft-deletes
./composer.json has been updated
Running composer update dyrynda/laravel-cascade-soft-deletes --with-dependencies
Loading composer repositories with package information
Dependency "laravel/framework" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dyrynda/laravel-cascade-soft-deletes ^4.1 -> satisfiable by dyrynda/laravel-cascade-soft-deletes[4.1.0].
    - dyrynda/laravel-cascade-soft-deletes 4.1.0 requires illuminate/database ^8.12 -> found illuminate/database[v8.12.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by boryn** [comment]
v4.1 is for PHP 8.0 version support and it requires "illuminate/database": "^8.12" which indeed may cause some backward compatibility problems.

Please have a look at the releases page: https://github.com/michaeldyrynda/laravel-cascade-soft-deletes/releases - maybe some previous versions like v4.0 or v3.0 will work for you.

Personally I use v3.0 which I installed by this command: `composer require dyrynda/laravel-cascade-soft-deletes:^3`
