### ISSUE TITLE
Undefined namespace

### ISSUE THREAD

**Issue by tokmakov** [michaeldyrynda/laravel-cascade-soft-deletes#45]
https://prnt.sc/zm7hgx

**Comment by michaeldyrynda** [comment]
The file and trait are where they ought to be per PSR-4.

Ensure you `composer dumpautoload` and that you are on the latest version of the package.

**Comment by tokmakov** [comment]
Thank you, it is my fault. Laravel version 7.30.0, php version 7.2.33. Last version laravel-...-deletes requires php 7.3. Run composer require dyrynda/laravel-...-deletes installs version 3. Version 3 use namespace Iatstuti\Database\Support\CascadeSoftDeletes, but I wrote use Dyrynda\Database\Support\CascadeSoftDeletes.
