### ISSUE TITLE
restore functionality?

### ISSUE THREAD

**Issue by holyboly** [michaeldyrynda/laravel-cascade-soft-deletes#51]
deleted_at timestamp would tell you if children were deleted from cascading event? not sure if its possible to be at a different second though or if the time of the delete command will be set on all deleted records

**Comment by michaeldyrynda** [comment]
Timestamp isn’t reliable enough for this; you’d have to track a delete batch ID or something so you can do the restore. 

It’s not something I’m planning on implementing in the package, though.
