### ISSUE TITLE
How to restore relational Data?

### ISSUE THREAD

**Issue by nikhil-lu210** [michaeldyrynda/laravel-cascade-soft-deletes#52]
Suppose **Post** has several **Comments**, and comment has several **Replies** too.
Now if I soft delete a Post, it automatically soft deleting all the comments and replies under that Post. But, when I want to restore a Post, its comments and replies are not getting restored.

What can I do for it?

I tried this way:
`Post::withTrashed()->whereId(1)->restore();`

**Comment by michaeldyrynda** [comment]
Please search for previous requests for this feature.
