### ISSUE TITLE
Polymorphic many to many pivot table support?

### ISSUE THREAD

**Issue by samhaiden** [michaeldyrynda/laravel-cascade-soft-deletes#66]
(apologies for the code blocks - the formatter is working for me)

When using this package on a polymorphic many to many relationship, the pivot table entries are forcefully deleted and not soft deleted when a parent record is deleted.

Here is my code:

**Parent Models receive the HasTag trait and this attribute:**
protected $cascadeDeletes = [
        "tags",
    ];

**HasTag Trait:**
public function tags(): MorphToMany
{
    return $this->morphToMany(Tag::class, "taggable:)->withTimestamps();
}

**Tag Model:**
class Tag extends BaseModel
{
    use HasFactory;
    use SoftDeletes;
    use CascadeSoftDeletes;

    public $table = "tags";
    protected $fillable = 
    [
        "tag",
        "slug",
    ];

    protected $cascadeDeletes = [
        "orders",
    ];

    public function orders()
    {
        return $this->morphedByMany(Order::class, "taggable");
    }
}

**Taggable Model:**
class Taggable extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $table = "taggables";
}

**Comment by michaeldyrynda** [comment]
Happy to review a PR that adds the functionality to the package, but I've not got the time to do this myself (in case the one year lag on replying to this issue wasn't indication enough, sorry! 😬)
