### ISSUE TITLE
Problem with forcedelete() i polimorphic Relation Many

### ISSUE THREAD

**Issue by MarcinStefaniak** [michaeldyrynda/laravel-cascade-soft-deletes#69]
Hi,
I have a problem with permanently deleting records.

Namely, I have the following models:

```
class Employee extends Model
{
     use SoftDeletes;
     use CascadeSoftDeletes;

     protected array $cascadeDeletes = ['addresses'];

     public function addresses(): MorphMany
     {
         return $this->morphMany(Address::class, 'addressable');
     }
     ...
}
```

```
class Address extends Model
{
    use SoftDeletes;
    ...
}
```

Soft delete works fine - data is written to the deleted_at column.

And when I call it, it removes only the employee and the addresses assigned only to him are still orphaned in the database.

`$employee->forceDelete();`

How can I permanently delete a record in such a relationship? So far I have not found an answer in issues.

**Comment by michaeldyrynda** [comment]
This package doesn't listen to the `forceDeleting` event, so the cascade isn't applied in those situations. You'll have to handle it yourself.
