### ISSUE TITLE
Recursive deleting

### ISSUE THREAD

**Issue by SirFlyann** [michaeldyrynda/laravel-cascade-soft-deletes#8]
Hello. I have this situation:

One category can have subcategories(they use the same model. The difference is that a subcategory have the ID of it's father, while the father category have the field 'FatherID' as NULL), and both can have posts on them. Something like this:

Category
    Father posts
    Subcategory
        Subcategory Posts

When I delete a father category, I need to softdelete it's posts, it's subcategories and their posts. However, I'm not being able to softdelete the subcategories posts. Can you help me with this ?

Thanks in advance. This package is awesome =).

**Comment by michaeldyrynda** [comment]
What do your relationship methods look like on the model? If you could provide some code to look at, it would make it simpler to see if we can find a solution to this situation. It should be possible.

In theory, it ought to be a matter of defining the posts of a category model to cascade when the delete is carried out. So your `Category` model would define a `posts` relationship, and simply define `posts` in the `$cascadeDeletes` property. When the `Category` is deleted - irrespective of whether it is a parent category or not - delete should still be called on the `posts` relationship.

**Comment by SirFlyann** [comment]
Sorry, I don't think I explained my problem perfectly. I need to delete a father, and the rest of the tree should be deleted with it. What happens is that the Subcategories posts are not being deleted. Anyway, the Model should help, and here it is.
Please note that a subcategory is also a Category.
![screenshot from 2016-06-30 09-26-12](https://cloud.githubusercontent.com/assets/13949991/16488030/b5f76c84-3ea4-11e6-8c69-bd12f362d5d1.png)

Here is the Category table, if you need it.
![screenshot from 2016-06-30 09-37-51](https://cloud.githubusercontent.com/assets/13949991/16488322/5928a71e-3ea6-11e6-89ed-6be00e5e89dd.png)
 
Sorry for any mistakes or dumb statements, I'm quite new to programming, and I'm not a native English speaker =).

**Comment by michaeldyrynda** [comment]
Thanks for clarifying @SirFlyann - I'll try and have a play with it on the weekend and see what needs to be done.

**Comment by SirFlyann** [comment]
You're welcome. I'll be waiting. Once again, thanks for the package =)

**Comment by michaeldyrynda** [comment]
Hey @SirFlyann, @schnittstabil submitted a pull request that I think should cover your use case here. Are you able to verify that (#9) for me? That way we can kill two birds with one stone.

**Comment by schnittstabil** [comment]
> I'm quite new to programming

@SirFlyann To verify the pull request, you might change your `composer.json`:

```json
{
    …
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/schnittstabil/laravel-cascade-soft-deletes"
        }
    ],
    "require": {
        …
        "iatstuti/laravel-cascade-soft-deletes": "dev-grandchildren"
        …
    },
    …
}
```

and, of course update your `vendor` directory:
```
composer update
```

After @michaeldyrynda released a new version, I will delete the `grandchildren` branch, hence you have to revert these changes though.

**Comment by SirFlyann** [comment]
Sure. I'll try it and tell you how it goes. Thanks =).

**Comment by SirFlyann** [comment]
Works perfectly. Sorry for the late response and thanks for your help @michaeldyrynda and @schnittstabil. =)

**Comment by michaeldyrynda** [comment]
Excellent, I've tagged the release as 1.0.4 including @schnittstabil's PR.
